### ISSUE TITLE
Is there a way to make tooltip position dynamically based on the screen view?

### ISSUE THREAD

**Issue by padmacnu** [yapplabs/ember-tether#26]
I have set the tooltip to be positioned bottom middle on the target. When the target is at the bottom of the screen, we want tooltip to dynamically change its position to top of the target instead of bottom and not visible to the user

**Comment by chrislopresto** [comment]
@padmacnu This sounds like a good use case for the constraints api that Hubspot Tether itself provides: http://github.hubspot.com/tether/ The constraints api provides many ways to manipulate the position of your tethers.

If the Hubspot Tether constraints api doesn't suit your needs, you could opt to change the `attachment` and `targetAttachment` properties of your `ember-tether` components. Changing these Ember component properties will immediately update the underlying tether. You'll just need to determine how and when to do so in your app.

I hope this helps. In either case, I don't think there's anything to add to the `ember-tether` addon codebase, so I'm going to close this issue.

Many folks might benefit from some better help in the `ember-tether` README for things like this. We would definitely accept a PR for anything helpful you might unearth.
