### ISSUE TITLE
peerDependencies warning in addons

### ISSUE THREAD

**Issue by sir-dunxalot** [yapplabs/ember-tether#38]
The [Readme](https://github.com/yapplabs/ember-tether#using-ember-tether-in-your-own-addon) states that one must use `peerDependencies` in order to use ember-tether in an addon.

This causes a warning for consuming applications of the addon that uses ember-tether. For example, this issue: https://github.com/sir-dunxalot/ember-tooltips/issues/73.

Are there any plans to get around the need to specify ember-tether as a peer dep? Or do you know of a workaround? Currently, my only other path is to do a multi-line install where the addon using ember-tether explicitly states that the developer should install ember-tether on their own first. However, that seems to go against the controlled modularity/dependency of Ember addons.

**Comment by sir-dunxalot** [comment]
I add that this is a low priority issue because it's just a warning but it's going to arise sooner or later when Ember CLI adopts NPM3.

**Comment by tomwayson** [comment]
actually I see that that @lukemelia removed those instructions from the README in 5eba0979ba12a4ee811de73b2c48a20e8c29b14c. Does that mean that we no longer have to use `peerDependency` when consuming ember-tether in an addon? Was there a change in that commit made this possible? I'm asking b/c I'd like try the changes in #27 to another addon, but that PR suggests that `peerDependencies` are needed.

**Comment by lukemelia** [comment]
I removed the instructions because they have proven unnecessary for us. We are running npm3, which may be the reason why that's the case. @chrislopresto do you recall why we used to advise this?

**Comment by lukemelia** [comment]
We eliminated the peerDependencies bit. Sorry for the confusion.
