### ISSUE TITLE
locate tether bottom left - top left

### ISSUE THREAD

**Issue by cbroeren** [yapplabs/ember-tether#7]
Is there a possibility to locate the tether on the bottom-left of the target? 

'''
targetAttachment: bottom left 
attachment: top left
'''

![pastedgraphic-1](https://cloud.githubusercontent.com/assets/7499806/8409033/f23355ba-1e74-11e5-9761-22b13bec4d17.png)

**Comment by chrislopresto** [comment]
Yes, and it looks just like the image you copied. The [live demo](http://yapplabs.github.io/ember-tether/) doesn't show that particular combination of values, so I hopped in the Ember Inspector to set the values that way:

https://www.evernote.com/l/AAN-_lyNqoRI-piJtQajmd5zQmUqNFNABEw

Ember Tether wraps Hubspot [Tether](http://github.hubspot.com/tether/), so their documentation page is the best place to dig into more detail about attachment, offset, constraints, etc..
